# Generated by Django 2.2.14 on 2020-09-17 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptCode', models.CharField(max_length=10)),
                ('deptFullName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=10)),
                ('courseFullName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subName', models.CharField(max_length=30)),
                ('subCode', models.CharField(max_length=10)),
                ('deptName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionPapers.Branch')),
                ('yearNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionPapers.Year')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionPaperFile', models.FileField(upload_to='attachments')),
                ('ofYear', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ex - 2020-2021', regex='^\\d{4}[-]\\d{4}')])),
                ('forSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionPapers.Subject')),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.FacultyDetail')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionPapers.Course'),
        ),
    ]
