language: python
sudo: false
python:
  - "2.7"
# command to install dependencies
install:
- pip install --upgrade pip
- pip install -r requirements/dev.txt
- pip install coveralls

# script: coverage
script:
  - flake8 ./

after_success: coveralls

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
